# Tugboat config.
# @see https://github.com/TugboatQA/Backdrop-CMS-Starter-Kit

services:
  php:
    image: tugboatqa/php:7.2-apache
    default: true
    depends: mariadb
    commands:
      init:
        - a2enmod headers rewrite
        - docker-php-ext-install opcache

        # Install Drush.
        - composer --no-ansi global require drush/drush:8.x
        - ln -sf ~/.composer/vendor/bin/drush /usr/local/bin/drush
        - mkdir -p ~/.drush/commands/
        - cd ~/.drush/commands/ && wget https://github.com/backdrop-contrib/drush/archive/1.x-1.x.zip
        - cd ~/.drush/commands/ && unzip 1.x-1.x.zip -d backdrop

        # Download Backdrop.
        - drush download-backdrop backdrop
        - ln -snf "${TUGBOAT_ROOT}/backdrop" "${DOCROOT}"

        # Setup install profile.
        - mkdir "${DOCROOT}/profiles"
        - ln -snf "${TUGBOAT_ROOT}/spam_challenge" "${DOCROOT}/profiles/spam_challenge"

        # Install Backdrop.
        - drush -r "${DOCROOT}" site-install spam_challenge --db-url="mysql://tugboat:tugboat@mariadb/tugboat" -y
        - drush -r "${DOCROOT}" user-password admin --password=d8b4uTTk6Mu7DBz7fe4B2u5G7DrQD1

        # Set file permissions.
        - mkdir -p "${DOCROOT}/files"
        - chown www-data "${DOCROOT}/files"
        - chmod 744 "${DOCROOT}/files"

      build:
        - drush -r "${DOCROOT}" cache-clear all
        - drush -r "${DOCROOT}" updatedb -y

  mariadb:
    image: tugboatqa/mariadb:10.1
